--liquibase formatted sql
--changeset higor:creating-tables

create TABLE PERSON (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(300) NOT NULL,
    BIRTH_DAY DATE NOT NULL
);

create TABLE ADDRESS (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    STREET_NAME VARCHAR(250) NOT NULL,
    ZIP_CODE VARCHAR(15) NOT NULL,
    NUMBER BIGINT NOT NULL,
    CITY VARCHAR(50) NOT NULL,
    MAIN_ADDRESS BOOLEAN NOT NULL,
    PERSON_ID BIGINT,
    CONSTRAINT PERSON_ID_FK FOREIGN KEY (PERSON_ID) REFERENCES PERSON(ID)
);
